# The three programs, built together. Generated by tools/make-projects.py.
#
#   make -f workspace.mk           what the editor drives, then the editor
#   make -f workspace.mk bin       and all four binaries in bin/
#   make -f workspace.mk check     and run every suite
#   make -f workspace.mk clean
#
# This is the Linux half of what RStudio.xcworkspace is on a Mac and
# RStudio.sln is on Windows: one thing to build, with ed1 after the two
# compilers it drives. It does not reimplement any of their builds - it calls
# the Makefile each repository already has, which is the only way this can stay
# true when one of them changes.
#
# The four are expected side by side. That is the one assumption here, and it
# is the same one the workspace and the solution make.

# Overridable, because they are not called this everywhere. On the Linux box
# the same two repositories are ~/ansicc and ~/shalimar:
#
#   make -f workspace.mk CC1_DIR=$HOME/ansicc SHC_DIR=$HOME/shalimar
CC1_DIR ?= ../Compiler-C
SHC_DIR ?= ../Compiler-S
C2S_DIR ?= ../Converter-C2S

# ---- one directory, named once and given to all four ------------------------
#
# Each of the four Makefiles takes a BINDIR saying where its finished program
# goes, and each defaults to its own repository - so building any one of them
# alone is exactly what it always was. This is the only place that overrides
# the four at once, because this is the only build that knows all four exist.
#
# The default is RStudio's own root, which is where RStudio.exe is built and
# therefore the directory the editor searches first: it finds the compilers it
# drives with path::besideProgram, before PATH, so that a compiler shipped with
# this copy is the one this copy runs.
#
# **Built into, not collected into.** The rule this replaces built the three in
# three places and copied them here afterwards, and a copy step is a step that
# can be incomplete - shc.exe arrived without the runtime archives it links,
# which no build and no suite could see and only pressing Run revealed.
# Nothing is copied now; the three are simply told where to write.
#
# Absolute, because each sub-make runs in its own directory and a relative path
# would mean three different places.
BINDIR ?= $(CURDIR)
OUT := $(abspath $(BINDIR))

.PHONY: all cc1 shc c2s editor confirm bin check clean

# `confirm` and not `editor`, so that the last thing a workspace build does is
# check that what the editor drives is actually beside it.
all: confirm

cc1:
	$(MAKE) -C $(CC1_DIR) BINDIR=$(OUT)

shc:
	$(MAKE) -C $(SHC_DIR) BINDIR=$(OUT)

# The converter. Not a compiler and nothing links it - the editor runs it over
# the open file from the Language menu - but it is found the same way the
# compilers are, beside the editor, so it is built into the same place.
#
# OBJDIR as well as BINDIR, which the other two do not need: Converter-C2S
# sets OBJDIR with := and its own objects would otherwise land in its tree
# while its binary landed here.
c2s:
	$(MAKE) -C $(C2S_DIR) BINDIR=$(OUT) OBJDIR=$(OUT)/obj-c2s

# The dependency, said the same way it is said in the other two: the editor is
# built after the things it drives. Nothing of them ends up inside it.
editor: cc1 shc c2s
	$(MAKE) BINDIR=$(OUT)

# Asked of RStudio rather than answered here. The editor is the thing that
# knows what it drives - the list is in its own Makefile, beside the code that
# goes looking for them - and this only calls it once all four have been
# built into one place.
confirm: editor
	$(MAKE) BINDIR=$(OUT) confirm

# Each suite is that project's own, called by the name that project uses -
# both compilers say `test` and only the editor says `check`. Calling `check`
# on all three was written first and failed on the first run, which is the
# argument for running one of these before believing it.
#
# And cc1's `test` is a Linux suite. It compares against gcc and runs x86-64
# binaries, so on a Mac it refuses and names what does run here instead. That
# refusal is cc1 being right, so this asks the host and runs what that host
# can - rather than the alternatives, which are to skip cc1 on a Mac or to
# ignore a failure and lose the real ones with it.
HOST := $(shell uname -s)

check: confirm
ifeq ($(HOST),Darwin)
	cd $(CC1_DIR) && ./tests/arm64.sh
	cd $(CC1_DIR) && ./tests/fingerprint.sh
else
	$(MAKE) -C $(CC1_DIR) test
endif
	$(MAKE) -C $(SHC_DIR) test
# The converter's suite is differential and needs both compilers as oracles.
# It is given the two just built into $(OUT), for the same reason the editor's
# is below: those are the ones this build produced, and they are the ones
# whose behaviour the converter's output is being judged against.
	$(MAKE) -C $(C2S_DIR) BINDIR=$(OUT) OBJDIR=$(OUT)/obj-c2s test CC1=$(OUT)/cc1.exe SHC=$(OUT)/shc.exe
# The two just built into $(OUT), and not the copies in the compilers' own
# trees. Those are usually the same file and occasionally are not, and the
# occasion is exactly the one worth catching: this build wrote its compilers
# somewhere, and this is the suite that says whether what it wrote works.
#
# Naming the wrong ones does not fail - the editor's suite skips the cases that
# need a compiler and says so quietly - so the count fell from 792 and 232 to
# 686 and 115 and everything still read as green. A suite that skips is not a
# suite that passes.
	$(MAKE) BINDIR=$(OUT) check CC1=$(OUT)/cc1.exe SHC=$(OUT)/shc.exe

# The alternative destination, for anyone who would rather the checkout root
# stayed as it was. Nothing is copied into it - see the `bin` rule below.
BIN := bin

# Emptied first. A binary that was renamed leaves its old self here otherwise,
# and a directory holding both cc1 and cc1.exe is one where nobody can say
# which was run.
# The same build, into bin/ instead of into the root - for anyone who would
# rather the checkout stayed clean. It is one line now because the three
# already take a BINDIR: this names a different one and gets out of the way.
#
# It used to be a second collector with a second destination, which is what
# made it possible for it to collect the wrong set. There is nothing here to
# get wrong any more.
bin:
	$(MAKE) -f workspace.mk BINDIR=$(CURDIR)/$(BIN)

clean:
	rm -rf $(BIN)
	$(MAKE) -C $(CC1_DIR) BINDIR=$(OUT) clean
	$(MAKE) -C $(SHC_DIR) BINDIR=$(OUT) clean
	$(MAKE) -C $(C2S_DIR) BINDIR=$(OUT) OBJDIR=$(OUT)/obj-c2s clean
	$(MAKE) BINDIR=$(OUT) clean
